apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: push-triggertemplate
  namespace: kabanero
spec:
  params:
  - name: repoName
    description: The git repository's name
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: namespace
    description: The namespace to create the resources
  - name: pipeline
    description: The Tekton pipeline to run
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source-$(uid)
      namespace: $(params.namespace)
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: docker-image-$(uid)
      namespace: $(params.namespace)
    spec:
      type: image
      params:
      - name: url
        value: image-registry.openshift-image-registry.svc:5000/$(params.namespace)/$(params.repoName)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: event-to-sink-$(uid)
      namespace: $(params.namespace)
    spec:
      type: cloudEvent
      params:
      - name: targetURI
        value: http://event-display.kabanero.svc.cluster.local
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: $(params.pipeline)-run-$(uid)
      namespace: $(params.namespace)
    spec:
      serviceAccountName: kabanero-operator
      pipelineRef:
        name: $(params.pipeline)
      resources:
      - name: git-source
        resourceRef:
          name: git-source-$(uid)
      - name: docker-image
        resourceRef:
          name: docker-image-$(uid)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: push-pipelinebinding
  namespace: kabanero
spec:
  params:
  - name: gitrevision
    value: $(body.after)
  - name: namespace
    value: kabanero
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: repoName
    value: $(body.repository.name)
  - name: pipeline
    value: $(body.kabanero.pipeline)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: push-listener
  namespace: kabanero
spec:
  serviceAccountName: kabanero-operator
  triggers:
  - binding:
      name: push-pipelinebinding
    template:
      name: push-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: push-listener
  name: push-listener-route
  namespace: kabanero
spec:
  host: getting-started-push.YOUR-DOMAIN-REPLACEME
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-push-listener
  wildcardPolicy: None
