apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tag-triggertemplate
  namespace: kabanero
spec:
  params:
  - name: repoName
    description: The git repository's name
  - name: namespace
    description: The namespace to create the resources
  - name: pipeline
    description: The Tekton pipeline to run
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: docker-from-image-$(uid)
      namespace: $(params.namespace)
    spec:
      type: image
      params:
      - name: url
        value: image-registry.openshift-image-registry.svc:5000/$(params.namespace)/$(params.repoName)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: docker-to-image-$(uid)
      namespace: $(params.namespace)
    spec:
      type: image
      params:
      - name: url
        value: image-registry.openshift-image-registry.svc:5000/$(params.repoName)-test/$(params.repoName)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: event-to-sink-$(uid)
      namespace: $(params.namespace)
    spec:
      type: cloudEvent
      params:
      - name: targetURI
        value: http://event-display.kabanero.svc.cluster.local
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: $(params.pipeline)-run-$(uid)
      namespace: $(params.namespace)
    spec:
      serviceAccountName: kabanero-operator
      pipelineRef:
        name: $(params.pipeline)
      resources:
      - name: docker-src-image
        resourceRef:
          name: docker-from-image-$(uid)
      - name: docker-dest-image
        resourceRef:
          name: docker-to-image-$(uid)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tag-pipelinebinding
  namespace: kabanero
spec:
  params:
  - name: repoName
    value: $(body.repository.name)
  - name: namespace
    value: kabanero
  - name: pipeline
    value: $(body.kabanero.pipeline)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tag-listener
  namespace: kabanero
spec:
  serviceAccountName: kabanero-operator
  triggers:
  - binding:
      name: tag-pipelinebinding
    template:
      name: tag-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: tag-listener
  name: tag-listener-route
  namespace: kabanero
spec:
  host: getting-started-tag.YOUR-DOMAIN-REPLACEME
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-tag-listener
  wildcardPolicy: None
