apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name:  {{.build.nameSuffix}}
  namespace: {{.build.namespace}}
spec:
  pipelineRef:
    name: {{.build.collectionID}}-build-only-pipeline
  resources:
  - name: git-source
    resourceRef:
      name: git-{{.build.nameSuffix}}
  serviceAccountName: {{.build.serviceAccountName}}
  timeout: {{.build.timeout}}
