apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: {{.build.nameSuffix}}
  namespace: {{.build.namespace}}
spec:
  serviceAccountName: {{.build.serviceAccountName}}
  timeout: 
  pipelineRef:
    name: {{.build.collectionID}}-image-retag-pl
  resources:
    - name: docker-src-image
      resourceRef:
        name: docker-from-{{.build.nameSuffix}}
    - name: docker-dest-image
      resourceRef:
        name: docker-to-{{.build.nameSuffix}}
